# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HarborCli < Formula
  desc "Harbor Unoffical CLi"
  homepage "https://github.com/hinyinlam/cli-for-harbor"
  version "0.0.2"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hinyinlam/cli-for-harbor-go/releases/download/v0.0.2/cli-for-harbor-go_0.0.2_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "462fc30c55958ea0df2b5a76d925132ff53a31186881fcc3710c8e4584dfdedb"

      def install
        bin.install "harbor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hinyinlam/cli-for-harbor-go/releases/download/v0.0.2/cli-for-harbor-go_0.0.2_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "a616666c96a5a113ac547509ad3c8a11aea982e170b35297c9ad3d1b5c95b45f"

      def install
        bin.install "harbor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hinyinlam/cli-for-harbor-go/releases/download/v0.0.2/cli-for-harbor-go_0.0.2_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d910169cd720fed5bfcd6cbdfa2103396e22d2703c630b246619dc0c74e2e3d1"

      def install
        bin.install "harbor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hinyinlam/cli-for-harbor-go/releases/download/v0.0.2/cli-for-harbor-go_0.0.2_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "807a3cdd187d3514dd4259de9ebe9c7141a9ca69420bfbb8140d15f551bb5729"

      def install
        bin.install "harbor"
      end
    end
  end

  def caveats; <<~EOS
    This is an unofficial Harbor CLI for CNCF Harbor Registry, not for production use
  EOS
  end

  test do
    system "#{bin}/harbor --version"
  end
end
