# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HarborCli < Formula
  desc "Harbor Unoffical CLi"
  homepage "https://github.com/hinyinlam/cli-for-harbor"
  version "0.0.4"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hinyinlam/cli-for-harbor/releases/download/v0.0.4/cli-for-harbor_0.0.4_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "73173566a7a7b0accaa58865de024a2d052396e3a6d65f181a00121e92148578"

      def install
        bin.install "harbor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hinyinlam/cli-for-harbor/releases/download/v0.0.4/cli-for-harbor_0.0.4_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "66d9980516f2845ccc1e137ee4c3cdfdb04b944b6af8e5585804c8262a6b5ff5"

      def install
        bin.install "harbor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hinyinlam/cli-for-harbor/releases/download/v0.0.4/cli-for-harbor_0.0.4_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "eb47017afd1577623b460026eab8977decc71a2b60054ed9213622e2d271d3b0"

      def install
        bin.install "harbor"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hinyinlam/cli-for-harbor/releases/download/v0.0.4/cli-for-harbor_0.0.4_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "ab8e7dafa27ef1eecdf1480c3f0b2bcf384c67b9bc539cf2205db9037ea75042"

      def install
        bin.install "harbor"
      end
    end
  end

  def caveats; <<~EOS
    This is an unofficial Harbor CLI for CNCF Harbor Registry, not for production use
  EOS
  end

  test do
    system "#{bin}/harbor --version"
  end
end
